site_name: UNNC CS Feiyue

theme:
  name: material
  # custom_dir: overrides

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - 25fall:
      - Overview: 25fall/overview.md
      - 01: 25fall/01_炒点土豆吃.md
      - 02: 25fall/02_CJR.md
      - 03: 25fall/03_rubyyy.md
      - 04: 25fall/04_FTTF.md
      - 05: 25fall/05_GQY.md
      - 06: 25fall/06_GMY.md
      - 07: 25fall/07_HK.md
      - 08: 25fall/08_HCH.md
      - 09: 25fall/09_HZK.md
      - 10: 25fall/10_Iridescent.md


